config/routes.rb
Rails.application.routes.draw do
  
  resources :blips

  root 'blips#index'

end

app/models/blip.rb
class Blip
  # These includes/extends are needed for form_for to work 
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :gid, :title, :summary, :link, :startTime, :endTime, :address, :lat, :lng

  # TODO MAKE SURE VALIDATIONS MATCH FINAL MODEL 

  validates :title, presence: true

  validates :title,       length: {maximum: 255}
  validates :summary,     length: {maximum: 255}
  validates :link,        length: {maximum: 255}
  validates :startTime,   length: {maximum: 255}
  validates :endTime,     length: {maximum: 255}
  validates :address,     length: {maximum: 255}

  # Constructor which will take in a hash and set all the respective 
  # attributes 
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  # Method needed for form_for to work 
  def persisted?
    false
  end

end

app/controllers/blips_controller.rb
class BlipsController < ApplicationController
  def new
    @blip = Blip.new                                                                      # make a new blip
  end

  def create
    validStartTime = validTimeHashHelper(params[:blip], "startTime")
    validEndTime   = validTimeHashHelper(params[:blip], "endTime")

    # Time Validity must be checked seperately: 
    # If the start and end times are valid, get rid of the datetime_select time tags
    # and put in an epoch time, if it isnt valid render the form with an error message
    if(validStartTime && validEndTime) 
      cleanParams = cleanHash(params[:blip])                                              # get rid of all key-value pairs where the value is "" 
      # If it was valid but all the values were "", then the cleanHash() would 
      # have already gotten rid of all the time tags and there is no need to do 
      # anything. On the other hand, if it was valid and had a time, then all the time 
      # tags must be removed and an epoch time must be added
      if(cleanParams.has_key?("startTime(1i)"))                                           # check if it had a startTime
        cleanParams[:startTime] = getEpoch(cleanParams, "startTime")                      # set the epoch start time
        cleanParams = removeTimeTags(cleanParams, "startTime")                            # get rid of all time tags for startTime
      end

      if(cleanParams.has_key?("endTime(1i)"))                                             # check if it had an endTime
        cleanParams[:endTime]   = getEpoch(cleanParams, "endTime")                        # set the epoch endTime
        cleanParams = removeTimeTags(cleanParams,"endTime")                               # get rid of all time tags for endTime
      end
    else
      ## If both times not valid: save valid datetime if one is valid, remove time tags, go
      ## back to the new form. Invalid datetimes will be erased and highlighted in red
      
      cleanParams = cleanHash(params[:blip])                                              # get rid of all key-value pairs where the value is "" 

      # If the times are valid and not nil then remember them so the datetime 
      # auto-fills to their values, otherwise will be blank 
      if(validStartTime && cleanParams.has_key?("startTime(1i)")) 
        cleanParams["startTime"] = Time.at(getEpoch(cleanParams, "startTime") / 1000)
      end
      if(validEndTime && cleanParams.has_key?("endTime(1i)"))
        cleanParams["endTime"] = Time.at(getEpoch(cleanParams, "endTime") / 1000)
      end

      # Get rid of the time tags (no exceptions thrown if tags not there)
      cleanParams = removeTimeTags(cleanParams, "startTime")
      cleanParams = removeTimeTags(cleanParams, "endTime")

      @blip = Blip.new(cleanParams)                                                                  # create the blip 
      @blip.valid?                                                                                   # generate all the other error messages as well
      @blip.errors[:startTime] = "must be blank or complete" unless validStartTime                   # if the start time is wrong add the error messages
      @blip.errors[:endTime]   = "must be blank or complete" unless validEndTime                     # if the end time is wrong add the error messages
      
      render :action => "new"                                                                        # render the new form
      return
    end

    newBlip = Blip.new(cleanParams)                                                                  # create the blip to check for validations / convert to json

    # Make sure that the blip is valid (checks everything but time), otherwise 
    # go back to the new view and render the errors. @blip will contain the errors
    unless newBlip.valid? 
      @blip = newBlip
      @blip.startTime = Time.at(@blip.startTime / 1000) unless @blip.startTime == nil
      @blip.endTime = Time.at(@blip.endTime / 1000) unless @blip.endTime == nil
      render :action => 'new'
      return
    end

    ## At this point the blip should be valid in all ways:

    newBlip.gid = 1                                                                       # TODO change from one to cookies[:gid]
    newBlip.lat = newBlip.lat.to_f if newBlip.lat.is_a? String                            # get rid of quotes
    newBlip.lng = newBlip.lng.to_f if newBlip.lng.is_a? String                            # get rid of quotes
        
    jsonBlip = newBlip.to_json                                                            # convert to JSON

    # Make post request to server in the JSON format
    c = Curl::Easy.http_post("#{HOST}:#{PORT_NUMBER}/api/v1/blip", jsonBlip   
    ) do |curl|
      curl.headers['Accept'] = 'application/json'
      curl.headers['Content-Type'] = 'application/json'
      curl.headers['Api-Version'] = '2.2'
    end

    redirect_to(:action => :index)                                                         # redirect to table with all blips
  end

  def edit
    blipRequest = Curl.get("#{HOST}:#{PORT_NUMBER}/api/v1/blip/#{params[:id]}")            # make a request for the blip that we will be editing
    @blipHash = JSON.parse(blipRequest.body_str)                                           # convert from JSON
    @blipHash.delete "id"                                                                  # delete ID from the hash because blips do not have that field
    @blip = Blip.new(@blipHash)                                                            # this will pre-populate the form

    @blip.startTime = Time.at(@blip.startTime / 1000) unless @blip.startTime == nil
    @blip.endTime = Time.at(@blip.endTime / 1000) unless @blip.endTime == nil
  end

  def update
    ## Behaviour very similar to create action

    blipRequest = Curl.get("#{HOST}:#{PORT_NUMBER}/api/v1/blip/#{params[:id]}")            # make a request for the original blip
    originalBlipHash = JSON.parse(blipRequest.body_str)                                    # convert from JSON

    originalStartTime = originalBlipHash["startTime"] / 1000 unless originalBlipHash["startTime"] == nil     # original start time    
    originalEndTime   = originalBlipHash["endTime"] / 1000 unless originalBlipHash["endTime"] == nil         # original end time

    validStartTime = validTimeHashHelper(params[:blip], "startTime")
    validEndTime   = validTimeHashHelper(params[:blip], "endTime")

    # Time Validity must be checked seperately: 
    # If the start and end times are valid, get rid of the datetime_select time tags
    # and put in an epoch time, if it isnt valid render the form with an error message
    if(validStartTime && validEndTime) 
      cleanParams = cleanHash(params[:blip])                                              # get rid of all key-value pairs where the value is "" 
      # If it was valid but all the values were "", then the cleanHash() would 
      # have already gotten rid of all the time tags and there is no need to do 
      # anything. On the other hand, if it was valid and had a time, then all the time 
      # tags must be removed and an epoch time must be added
      if(cleanParams.has_key?("startTime(1i)"))                                           # check if it had a startTime
        cleanParams[:startTime] = getEpoch(cleanParams, "startTime")                      # set the epoch start time
        cleanParams = removeTimeTags(cleanParams, "startTime")                            # get rid of all time tags for startTime
      end

      if(cleanParams.has_key?("endTime(1i)"))                                             # check if it had an endTime
        cleanParams[:endTime]   = getEpoch(cleanParams, "endTime")                        # set the epoch endTime
        cleanParams = removeTimeTags(cleanParams,"endTime")                               # get rid of all time tags for endTime
      end
    else
      ## If both times not valid: save valid datetime if one is valid, remove time tags, go
      ## back to the edit form. Invalid datetimes will be set to original values and highlighted in red
      
      cleanParams = cleanHash(params[:blip])                                              # get rid of all key-value pairs where the value is "" 

      # If the times are valid and not nil then remember them so the datetime 
      # auto-fills to their values, otherwise set them to the original times
      if(validStartTime) 
        if cleanParams.has_key?("startTime(1i)")
          cleanParams["startTime"] = Time.at(getEpoch(cleanParams, "startTime") / 1000)
        end
      else
        cleanParams["startTime"] = Time.at(originalStartTime) unless originalStartTime == nil
      end
      
      if(validEndTime)
        if cleanParams.has_key?("endTime(1i)")
          cleanParams["endTime"] = Time.at(getEpoch(cleanParams, "endTime") / 1000)
        end
      else
        cleanParams["endTime"] = Time.at(originalEndTime) unless originalEndTime == nil   
      end


      # Get rid of the time tags (no exceptions thrown if tags not there)
      cleanParams = removeTimeTags(cleanParams, "startTime")
      cleanParams = removeTimeTags(cleanParams, "endTime")

      @blip = Blip.new(cleanParams)                                                                  # create the blip 
      @blip.valid?                                                                                   # generate all the other error messages as well
      @blip.errors[:startTime] = "must be blank or complete" unless validStartTime                   # if the start time is wrong add the error messages
      @blip.errors[:endTime]   = "must be blank or complete" unless validEndTime                     # if the end time is wrong add the error messages
     
      render :action => "edit"                                                                       # render the edit form
      return
    end

app/helpers/blips_helper.rb
module BlipsHelper

  def timeHumanReadable(epochInt)
  	return nil if epochInt == nil 							# Time.at cant handle nil value so return nil if int is nil
    epochNoMili = epochInt / 1000							# Get rid of miliseconds for ease of use with ruby Time class
    return Time.at(epochNoMili).asctime						# asctime formats a nice string for you
  end

end

app/views/blips/_form.html.erb
<div class="row"> 
  <div class="col-md-6">
    <% if @blip.errors[:title].present? %>
      <div class="form-label-error"><span class="form-label">Title - </span><%= @blip.errors[:title].first %> </div>
    <% else %>
      <div class="form-label">Title</div>
    <% end %>
    <div class="form-field">
      <% if @blip.errors[:title].present? %> 
        <%= f.text_field :title, class: 'form-control error-red' %>
      <% else %>
        <%= f.text_field :title, class: 'form-control' %>
      <% end %>
    </div>

    <% if @blip.errors[:link].present? %>
      <div class="form-label-error"><span class="form-label">Link - </span><%= @blip.errors[:link].first %> </div>
    <% else %>
      <div class="form-label"> Link </div>
    <% end %>
    <div class="form-field">
      <% if @blip.errors[:link].present? %>
        <%= f.text_field :link, class: 'form-control error-red' %>
      <% else %>
        <%= f.text_field :link, class: 'form-control' %>
      <% end %>
    </div>

    <div class="row">
      <div class="col-md-6">
        <% if @blip.errors[:startTime].present? %>
          <div class="form-label-error"><span class="form-label">Start Time - </span><%= @blip.errors[:startTime].first %> </div>
        <% else %>
          <div class="form-label">Start Time</div>
        <% end %>
        <div class="form-field">
          <% if @blip.errors[:startTime].present? %>
            <div class="error-red"><%= f.datetime_select :startTime,  :include_blank => true , start_year: Date.today.year , end_year: Date.today.year + 5 , class: 'form-control' %></div>
          <% else %>
            <%= f.datetime_select :startTime,  :include_blank => true , start_year: Date.today.year , end_year: Date.today.year + 5 , class: 'form-control' %>
          <% end %>  
        </div>
      </div>

      <div class="col-md-6">
        <div style="float:right">
          <% if @blip.errors[:endTime].present? %>
            <div class="form-label-error"><span class="form-label">End Time - </span><%= @blip.errors[:endTime].first %> </div>
          <% else %>
            <div class="form-label">End Time</div>
          <% end %>
          <div class="form-field">
            <% if @blip.errors[:endTime].present? %>
              <div class="error-red"><%= f.datetime_select :endTime,  :include_blank => true , start_year: Date.today.year , end_year: Date.today.year + 5 , class: 'form-control' %></div>
            <% else %>
              <%= f.datetime_select :endTime,  :include_blank => true , start_year: Date.today.year , end_year: Date.today.year + 5 , class: 'form-control' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <% if @blip.errors[:summary].present? %>
      <div class="form-label-error"><span class="form-label">Summary - </span><%= @blip.errors[:summary].first %> </div>
    <% else %>
      <div class="form-label">Summary</div>
    <% end %>
    <div class="form-field">
      <% if @blip.errors[:summary].present? %>
        <%= f.text_area :summary, rows: "8", class: 'form-control error-red form-text-area' %>
      <% else %>
        <%= f.text_area :summary, rows: "8", class: 'form-control form-text-area' %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">

  <div class="col-md-6"> 
    <% if @blip.errors[:address].present? %>
      <div class="form-label-error"><span class="form-label">Address - </span><%= @blip.errors[:address].first %> </div>
    <% else %>
      <div class="form-label">Address</div>
    <% end %>
    <div class="form-field">
      <% if @blip.errors[:address].present? %>
        <%= f.text_field :address, class: 'form-control error-red' %>
      <% else %>
        <%= f.text_field :address, class: 'form-control' %>
      <% end %>
    </div>
  </div>

    
  <div class="col-md-3">
    <% if @blip.errors[:lat].present? %>
      <div class="form-label-error"><span class="form-label">Latitude - </span><%= @blip.errors[:lat].first %> </div>
    <% else %>
      <div class="form-label">Latitude</div>
    <% end %>
    <div class="form-field" style="margin: 0px 0px 0px 0px">
      <% if @blip.errors[:lat].present? %>
        <%= f.number_field :lat, :step => 'any',  class: 'form-control error-red' %>
      <% else %>
        <%= f.number_field :lat, :step => 'any',  class: 'form-control' %>
      <% end %>
    </div>
  </div>

  <div class="col-md-3">
    <% if @blip.errors[:lng].present? %>
      <div class="form-label-error"><span class="form-label">Longitude - </span><%= @blip.errors[:lng].first %> </div>
    <% else %>
      <div class="form-label">Longitude</div>
    <% end %>
    <div class="form-field" style="margin: 0px 0px 0px 0px">
      <% if @blip.errors[:lng].present? %>
        <%= f.number_field :lng, :step => 'any',  class: 'form-control error-red' %>
      <% else %>
        <%= f.number_field :lng, :step => 'any',  class: 'form-control' %>
      <% end %>
    </div>
  </div>

</div>

app/views/blips/edit.html.erb
<h1 class="title-of-page form-page">Update</h1>
<div class="col-md-1"></div>
<div class="col-md-10"> 
	<%= form_for @blip , :url => {:action => "update"} , :html => {:method => 'put', class: 'form'} do|f| %>
	  
	  <%= render :partial => 'form', :locals =>{:f => f}%>

	  <div class="form-button">  
	 	  <%= button_tag(type: 'submit', class: "btn btn-success btn-lg") do %>
	 		<i class="glyphicon glyphicon-floppy-disk"></i>&nbsp;Update Blip
	  	  <% end %>
	  </div> 

	  <%= link_to root_path, class: "btn btn-primary btn-lg home-button" do%>
		<i class="glyphicon glyphicon-home"></i> &nbsp;Home
	  <% end %>



	<% end %>


</div>
<div class="col-md-1"></div>

app/views/blips/index.html.erb
<h1 class="title-of-page">Blips</h1>

<table class="table table-striped table-bordered table-condensed" id="fixed-table">
  <thead>
  <tr>
    <th class="col-md-2">Title</th>
    <th class="col-md-3">Summary</th>
    <th class="col-md-1">Link</th>
    <th class="col-md-1">Start Time</th>
    <th class="col-md-1">End Time</th>
    <th class="col-md-1">Address</th>
    <th class="col-md-1">Latitude</th>
    <th class="col-md-1">Longitude</th>
    <th class="col-md-2">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% unless @blipsArray.empty? %>
      <% @blipsArray.each do |blipHash| %>
          <tr>
            <td><div class="fixed-table-data"><%= blipHash["title"]                                                                               %></div></td>
            <td><div class="fixed-table-data"><%= blipHash["summary"]                                                                             %></div></td>
            <td><div class="fixed-table-data" style="overflow:hidden"><%= link_to blipHash["link"],blipHash["link"] if blipHash["link"] != nil    %></div></td>
            <td><div class="fixed-table-data"><%= timeHumanReadable(blipHash["startTime"])                                                        %></div></td>
            <td><div class="fixed-table-data"><%= timeHumanReadable(blipHash["endTime"])                                                          %></div></td>
            <td><div class="fixed-table-data"><%= blipHash["address"]                                                                             %></div></td>
            <td><div class="fixed-table-data"><%= blipHash["lat"]                                                                                 %></div></td>
            <td><div class="fixed-table-data"><%= blipHash["lng"]                                                                                 %></div></td>

            <td>
              <%= link_to "Show", {:action => "show" , :id => blipHash["id"]}, class: "btn btn-small" %>
              <%= link_to "Edit", {:action => "edit" , :id => blipHash["id"]}, class: "btn btn-small" %>
              <%= link_to "Delete", {:action => "destroy", :id => blipHash["id"]}, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-small" %>
            </td>
          </tr>
      <% end %>
  <% else %>
      <tr>
        <td>Hello Club President! Welcome! Send your first blip by clicking the + icon below</td>
      </tr>
  <% end %>
  </tbody>

</table>

<div class="contextual table-button">
  <%= link_to(new_blip_path, class: "btn btn-success btn-lg") do %>
      <i class="glyphicon glyphicon-plus"></i> &nbsp;New Blip
  <% end %>
</div>

app/views/blips/new.html.erb
<h1 class="title-of-page form-page">Create</h1>
<div class="col-md-1"></div>
<div class="col-md-10"> 
	<%= form_for @blip , html: {class: 'form'} do|f| %>

	  <%= render :partial => 'form', :locals =>{:f => f}%>

	  <div class="form-button">
	    <%= button_tag(type: 'submit', class: "btn btn-success btn-lg") do %>
	 		<i class="glyphicon glyphicon-ok"></i>&nbsp;Create Blip
	  	<% end %>
	  </div>

	  <%= link_to root_path, class: "btn btn-primary btn-lg home-button" do%>
		  <i class="glyphicon glyphicon-home"></i> &nbsp;Home
	  <% end %>

	<% end %>
</div>
<div class="col-md-1"></div>

<br />

app/views/blips/show.html.erb
<h1><%= @blipHash["title"] %></h1>
<h2><%= @blipHash["summary"]%></h1>
<h3><%= @blipHash["address"] %></h1>

<% if (@blipHash["lat"] != nil && @blipHash["lng"] != nil) %>
	<h5><%= "Latitude: #{@blipHash["lat"]} Longitude: #{@blipHash["lng"]}" %></h1>
<% end %>

<h3><%= @blipHash["startTime"] %></h3>
<h3><%= @blipHash["endTime"] %></h3>

<br />

<% if @blipHash["link"] != nil %>
	<h4><%= link_to @blipHash["link"] , @blipHash["link"] %></h1>
<% end %>

<br />
<br />

<%= link_to root_path, class: "btn btn-primary btn-lg" do%>
	<i class="glyphicon glyphicon-home"></i> &nbsp;Home
<% end %>